name: Build & Deploy to one.com

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build
        env:
          TINA_CLIENT_ID: bf437fba-d60c-427e-87f3-cd38cba906b3
          TINA_TOKEN: 55d1bafcb0a9b6cd58f30a77c3e2e7bd09c484a4
          GITHUB_REF_NAME: main

      - name: Deploy to one.com via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.sweafs.se
          username: efe.gencer@icloud.com
          password: ${{ secrets.pass1 }}
          local-dir: ./dist/
          server-dir: /www/
          dangerous-clean-slate: false
